config/routes.rb
Rails.application.routes.draw do

  require 'resque/server'
  mount Resque::Server, at: '/jobs'
  mount ActionCable.server => '/cable'
  get 'products/index'

  get 'user/shop_list', to: 'users#shop_list', as: 'shop_list'
  get 'user/signup', to: 'users#signup', as: 'signup'
  post 'user/create', to: 'users#create'
  get 'user/signin', to: 'users#signin', as: 'signin'
  post 'user/login', to: 'users#login'
  get 'user/signout', to: 'users#signout', as: 'signout'

  resources :shops do
    resources :products
  end
  root 'shops#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shop.rb
class Shop < ApplicationRecord
	belongs_to :user, inverse_of: :shop #, optional: true
	has_many :product, inverse_of: :shop
    
	validates :shop_name, presence: true, length: { minimum: 3 }
	validates :shop_addr, presence: true, length: { minimum: 5 } #allow_blank
	validates :shop_desc, presence: true, length: { minimum: 5 } #allow_blank
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :if_unauthorize, except: [:index,:show]
    #https://www.youtube.com/watch?v=KADfCLGQWmI #register
  def index
    # @shops = Shop.all
    # HourlyEmailJob.perform_later()
    # SignupMailer.thanks_singup(@user).deliver_later
    @shops = Shop.paginate(:page => params[:page], :per_page => 5 )
  end

  def new
    WebNotificationsChannel.broadcast_to(
            current_user,
            title: 'New things!',
            body: 'All the news fit to print'
          )
    @shop = Shop.new
  end

  def show
    begin
      @shop = Shop.includes(:product).order("products.id DESC").find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:error] = 'No Shop Found.'
      redirect_to shops_url
    end
  end

  def create
    @user = User.find(session[:current_user_id])
    @shop = @user.shop.create(shop_parameters)
    if @shop.save
      redirect_to @shop
    else
      render 'new'
    end
  end

  def edit
    @shop = User.find(session[:current_user_id]).shop
    if @shop.nil?
      flash[:alert] = 'You don\'t have a shop'
      redirect_to shops_url
    elsif @shop.ids.include?(params[:id].to_i)
        @shop = Shop.find(params[:id].to_i)
    else
      flash[:alert] = 'It is not your shop'
      redirect_to shops_url
    end    
  end

  def update
    @shop = Shop.find(params[:id])
    if @shop.update(shop_parameters)
      flash[:notice] = 'Successfully updated your shop'
      redirect_to @shop
    else
      render 'edit'
    end
  end

  def destory
    @shop = Shop.find(params[:id])
    @shop.destory
    redirect_to @shops_path
  end

  private
  def shop_parameters
    params.require(:shop).permit(:shop_name,:shop_addr,:shop_desc)
  end

end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/shops/edit.html.erb
<%= form_with(model: @shop, local: true) do |f| %>
<% if @shop.errors.any? %>
<ul>
<% @shop.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>
</ul>
<% end %>

<p>
<%= f.label :Name %><br/>
<%= f.text_field :shop_name, { class: 'shop_name'} %>
</p>

<p>
<%= f.label :Address %><br/>
<%= f.text_field :shop_addr, { class: 'shop_addr'} %>
</p>

<p>
<%= f.label :Descripton %><br/>
<%= f.text_area :shop_desc, { class: 'shop_desc'} %>
</p>

<p><%= f.submit %></p>
<% end %>
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12" style="text-align: center;">
<h3>Shop List</h3>
</div>
</div>
<div class="row">
    <% @shops.each do |shop| %>
	<div class="col-xs-12 col-sm-8 offset-sm-2 col-md-8 offset-md-2 each-shop"
 style="height: auto;padding: 5px 15px;margin-bottom: 25px;">
 <div style="height: auto;width: 100%;border-bottom:0 solid #e1e1e1;padding: 5px;">
	<p><b>Name </b><%= shop.shop_name.blank?? "NA": shop.shop_name %></p>
	<p><b>Address </b><%= shop.shop_addr.blank?? "NA": shop.shop_addr %></p>
	<p><b>Description </b><%= shop.shop_desc.blank?? "NA": shop.shop_desc %></p>
	<% if is_current_user(shop.user_id) %>
	<p><%= link_to 'Edit', edit_shop_path(shop) %></p>
	<% end %>
	<p><%= link_to 'View details', shop_path(shop), class: 'btn btn-secondary', role: 'button' %></p>
	</div>
	</div>
	<% end %>
</div>
 <div class="col-xs-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 pagination-wrap">
 	<%= will_paginate @posts %>
 </div>

<style type="text/css">
	.pagination-wrap {
		height: auto;
		padding: 5px;
	}
	.pagination-wrap .pagination {
		height: auto;
		margin-top: 10px;
		padding: 7px 5px;
		border-radius: 0;
		text-align: center;
	}
	.pagination-wrap .pagination span,
	.pagination-wrap .pagination a {
		padding: 0 6px;
	}
</style>

app/views/shops/new.html.erb
<%# form_for @shop, url: {action: 'create'}, html: { class: 'shop_form'} do |f| %>
<%= form_with scope: :shop,url: shops_path, local: true do |f| %>

<% if @shop.errors.any? %>
<ul>
<% @shop.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>
</ul>
<% end %>

<p>
<%= f.label :Name %><br/>
<%= f.text_field :shop_name, { class: 'shop_name'} %>
</p>

<p>
<%= f.label :Address %><br/>
<%= f.text_field :shop_addr, { class: 'shop_addr'} %>
</p>

<p>
<%= f.label :Descripton %><br/>
<%= f.text_area :shop_desc, { class: 'shop_desc'} %>
</p>

<p><%= f.submit %></p>
<% end %>
<p><%= link_to 'Shop List', shops_path %></p>

app/views/shops/show.html.erb
<div class="row">
<div class="col-xs-12 col-sm-8 offset-sm-2 col-md-8 offset-md-2">
<h3><%= @shop.shop_name %></h3>
<p><b>Address: </b><%= @shop.shop_addr.nil?? "N/A": @shop.shop_addr %></p>
<p><b>Description: </b><%= @shop.shop_desc %></p>
<% if is_current_user(@shop.user_id) %>
<span><%= link_to 'Edit Shop', edit_shop_path(@shop) %></span>
<% end %>
</div>
</div>

<div class="row">
<div class="col-md-12 col-sm-12 col-xs-12" style="text-align: center;">
	<h4>Product List<span style="
	font-size: 13px;"> / <%= link_to 'New Product', new_shop_product_url(@shop) %></span></h4>
</div>

<% if @shop.product.length > 0 %>
<% @shop.product.each do |product| %>
<div class="col-xs-12 col-sm-8 offset-sm-2 col-md-8 offset-md-2 each-product"
 style="height: auto;padding: 5px 15px;margin-bottom: 25px;">
 <div style="height: auto;width: 100%;border-bottom:0 solid #e1e1e1;padding: 5px;">
	<h4><%= product.product_name %></h4>
	<p><b>Shop Descriptioin</b><br/><%= product.product_desc %></p>

	<% if is_current_user(@shop.user_id) %>
	<span><%= link_to 'Edit', edit_shop_product_path(@shop, product) %></span> / 
	<span><%= link_to 'Destroy', shop_product_path(@shop, product),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></span> / 
	<% end %>

	<span><%= link_to 'View', shop_product_url(@shop, product) %></span>
</div>
</div>
<% end %>
<% end %>

</div>