config/routes.rb
Rails.application.routes.draw do

  require 'resque/server'
  mount Resque::Server, at: '/jobs'
  mount ActionCable.server => '/cable'
  get 'products/index'

  get 'user/shop_list', to: 'users#shop_list', as: 'shop_list'
  get 'user/signup', to: 'users#signup', as: 'signup'
  post 'user/create', to: 'users#create'
  get 'user/signin', to: 'users#signin', as: 'signin'
  post 'user/login', to: 'users#login'
  get 'user/signout', to: 'users#signout', as: 'signout'

  resources :shops do
    resources :products
  end
  root 'shops#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">
    <title>ShopPro</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', 'bootstrap.min', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <!-- <link href="jumbotron.css" rel="stylesheet"> -->
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <%= link_to "ShopPro", root_url, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Shop', shops_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Product', products_index_path, class: 'nav-link' %>
          </li>
          <% if logged_in %>
          <li class="nav-item">
              <%= link_to 'New Shop', new_shop_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', signout_url, class: "nav-link" %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to  'Signin', signin_url, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to  'Signup', signup_url, class: "nav-link"%>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <main role="main">
    <div class="jumbotron">
        <div class="container" style="padding-top: 50px;">
          <h3>Put Your Shops Right Here!</h3>
          <p>List your products on.</p>
          <p id='comments'></p>
        </div>
      </div>
      <div class="container" style="margin-top: 5px;">
        <!-- Example row of columns -->
        <% flash.each do |name, msg| -%>
          <%= content_tag :div, msg, class: name %>
        <% end %>
        <%= yield %>
      </div> <!-- /container -->

    </main>

    <footer class="container" style="text-align: center;">
      <p>&copy; Company 2017-2018</p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag 'jquery-3.3.1.slim.min', 'popper.min', 'bootstrap.min', 'data-turbolinks-track': 'reload' %>
    <style type="text/css">
      /*Grid CSS*/
   /*   body {
  padding-top: 2rem;
  padding-bottom: 2rem;
}

h3 {
  margin-top: 2rem;
}

.row {
  margin-bottom: 1rem;
}
.row .row {
  margin-top: 1rem;
  margin-bottom: 0;
}
[class*="col-"] {
  padding-top: 1rem;
  padding-bottom: 1rem;
  background-color: rgba(86, 61, 124, .15);
  border: 1px solid rgba(86, 61, 124, .2);
}

hr {
  margin-top: 2rem;
  margin-bottom: 2rem;
}*/
    </style>
  </body>
</html>